version: '3.8'

services:
    backend:
        build: .
        container_name: template_api_backend
        ports:
            - '5000:5000' # Map port 5000 of the container to port 5000 on the host
        environment:
            NODE_ENV: production
        volumes:
            - .:/app # Mount the current directory to the /app directory in the container
        networks:
            - backend_network

networks:
    backend_network:
        driver: bridge
